name: Resuable Integration Testing Workflow

on: 
  workflow_call:
    inputs:
      runner-os:
        default: ubuntu-latest
        required: false
        type: string
      environment:
        default: development
        required: true
        type: string
    
jobs:
  dev-integration-testing:
    name: ${{ inputs.environment }} integration testing
    runs-on: ${{ inputs.runner-os }}
    steps:
    - name: Test Application Endpoints
      env:
        URL: ${{ needs.dev-deploy.outputs.app-endpoints }}
      run: |
        echo $URL
        # curl https://$URL/live -s -k | jq -r .status | grep -i live
