name: Solar System Workflow

on: 
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/*'
    
jobs:
  unit-testing:
    name: Unit Testing
    runs-on: ubuntu-latest
    # container:
    #   image: node:20
    services:
      mongo-db:
        image: siddharth67/mongo-db:non-prod
        ports:
        - 27017:27017
        # options:
        #   --name mongo
    env:
      MONGO_URI: mongodb://localhost:27017/superData
      MONGO_USERNAME: non-prod-user
      MONGO_PASSWORD: non-prod-password
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Setup NodeJS Version
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Get npm cache directory
      id: npm-cache-dir
      shell: bash
      run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}
    - name: Cache NPM dependencies
      uses: actions/cache@v4
      id: npm-cache
      with:
        path: ${{ steps.npm-cache-dir.outputs.dir }}
        key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
    - name: Install Dependencies
      run: npm install
    - name: Unit Testing
      run: npm test
    - name: Archive Test Result
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: Mocha-Test-Result
        path: test-results.xml
  code-coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    container:
      image: node:20
    services:
      mongo-db:
        image: siddharth67/mongo-db:non-prod
        options:
          --name mongo
    env:
      MONGO_URI: mongodb://mongo/superData
      MONGO_USERNAME: non-prod-user
      MONGO_PASSWORD: non-prod-password
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    # - name: Setup NodeJS Version
    #   uses: actions/setup-node@v4
    #   with:
    #     node-version: 20
    - name: Get npm cache directory
      id: npm-cache-dir
      shell: bash
      run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}
    - name: Cache NPM dependencies
      id: npm-cache 
      uses: actions/cache@v4
      with:
        path: ${{ steps.npm-cache-dir.outputs.dir }}
        key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
    - name: Install Dependencies
      run: npm install
    - name: Run Code-coverage
      run: npm run coverage
      continue-on-error: true
    - name: Archive Code-coverage Result
      uses: actions/upload-artifact@v4
      with:
        name: Code-Coverage-Result
        path: coverage
        retention-days: 5
  docker:
    needs: [unit-testing, code-coverage]
    name: Contanarize
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ghcr.io/mrinmoihossain/solar-system:${{ github.sha }}
  dev-deploy:
    if: contains(github.ref, 'feature/')
    needs: [docker]
    uses: ./.github/workflows/reuse-deployment.yml
    with:
      runner-os: ubuntu-latest
      environment: development
      k8s-manifest-dir: kubernetes/development
    secrets:
      k8s-kubeconfig: ${{ secrets.KUBECONFIG }}
  dev-integration-testing:
    if: contains(github.ref, 'feature/')
    needs: [dev-deploy]
    name: Development Integration Testing
    runs-on: ubuntu-latest
    environment:
      name: development
    steps:
    - name: Test Application Endpoints
      env:
        URL: ${{ needs.dev-deploy.outputs.APP_INGRESS_HOST }}
      run: |
        echo $URL
        # curl https://$URL/live -s -k | jq -r .status | grep -i live
  prod-deploy:
    if: github.ref == 'refs/heads/main'
    needs: [docker]
    name: Production Deploy
    runs-on: ubuntu-latest
    environment:
      name: production
    outputs:
      APP_INGRESS_HOST: ${{ steps.applicaiton-endpoints.outputs.APP_INGRESS_HOST }}
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Kubectl Setup
      uses: azure/setup-kubectl@v4
      with:
        version: v1.26.0
    - name: Kubeconfig Setup
      uses: azure/k8s-set-context@v4
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.KUBECONFIG }}
    # - name: Kubectl Version
    #   run: kubectl version --short -o yaml
    - name: Ingress IP Setup
      run: |
        # echo "INGRESS_IP=$(kubectl -n ingress-nginx get services ingress-nginx-controller -o jsonpath='{.status.loadBalancer.ingress[0].ip}')" >> $GITHUB_ENV
        echo "INGRESS_IP=12.13.14.11" >> $GITHUB_ENV
    - name: Replace Information
      uses: cschleiden/replace-tokens@v1
      with:
        tokenPrefix: '_{_'
        tokenSuffix: '_}_'
        files: '["kubernetes/production/*.yaml"]'
      env:
        NAMESPACE: ${{ vars.NAMESPACE }}
        REPLICAS: ${{ vars.REPLICAS }}
        IMAGE: ghcr.io/mrinmoihossain/solar-system:${{ github.sha }}
        INGRESS_IP: ${{ env.INGRESS_IP }}
    - name: Read the Kube-manifest Files
      run: cat kubernetes/production/*.yaml
    - name: Setup the Application Endpoints
      id: applicaiton-endpoints
      run: |
        # echo "APP_INGRESS_HOST=$(kubectl -n ${{ vars.NAMESPACE }} get ingress -o jsonpath="{.items[0].spec.tls[0].hosts[0]}")"
        echo "APP_INGRESS_HOST=12.13.14.16" >> $GITHUB_OUTPUT
  prod-integration-testing:
    if: github.ref == 'refs/heads/main'
    needs: [prod-deploy]
    name: Production Integration Testing
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
    - name: Test Application Endpoints
      env:
        URL: ${{ needs.prod-deploy.outputs.APP_INGRESS_HOST }}
      run: |
        echo $URL
        # curl https://$URL/live -s -k | jq -r .status | grep -i live
